name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  windows:
    name: CI for Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: .\scripts\windows\setup.ps1

      - name: Configure
        run: |
          mkdir build -Force
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest -C debug --test-dir test/

  macOS:
    name: CI for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: zsh scripts/macos/setup.sh

      - name: Install Ninja
        run: brew install ninja

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -GNinja ..

      - name: Build
        run: |
          cd build
          ninja

      - name: Test
        run: |
          cd build
          ctest -C debug --test-dir test/

  linux:
    name: CI for Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: bash scripts/linux/setup.sh

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -GNinja ..

      - name: Build
        run: |
          cd build
          ninja

      - name: Test
        run: |
          cd build
          ctest -C debug --test-dir test/
